<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909144605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table de reference tva + taux applicables (20 / 10 / 5,5 / 0 %)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tva (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taux NUMERIC(5, 2) NOT NULL, libelle VARCHAR(100) NOT NULL, actif BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TVA_TAUX ON tva (taux)');

        $this->addSql(<<<'SQL'
            INSERT INTO tva (taux, libelle, actif, position) VALUES
                (20.00, 'Taux normal', true, 0),
                (10.00, 'Travaux de renovation (logement de plus de 2 ans)', true, 1),
                (5.50, 'Renovation energetique', true, 2),
                (0.00, 'Non applicable / exonere', true, 3)
            SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE tva');
    }
}
