<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909151725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table entreprise (singleton) + ligne de configuration initiale a completer';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE entreprise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, siret VARCHAR(14) DEFAULT NULL, numero_tva_intracom VARCHAR(20) DEFAULT NULL, telephone VARCHAR(30) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, mentions_legales TEXT DEFAULT NULL, conditions_paiement TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, delai_validite_devis_jours INT DEFAULT 30 NOT NULL, adresse_ligne1 VARCHAR(255) DEFAULT NULL, adresse_ligne2 VARCHAR(255) DEFAULT NULL, adresse_code_postal VARCHAR(16) DEFAULT NULL, adresse_ville VARCHAR(255) DEFAULT NULL, adresse_pays VARCHAR(100) DEFAULT \'France\', PRIMARY KEY (id))');

        // Ligne unique de configuration : les champs restants sont a completer
        // depuis le back-office.
        $this->addSql("INSERT INTO entreprise (nom, delai_validite_devis_jours, adresse_pays) VALUES ('Jason Renovation', 30, 'France')");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE entreprise');
    }
}
