<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909151057 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table de reference unite + unites de mesure courantes du batiment';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE unite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, libelle VARCHAR(50) NOT NULL, actif BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_UNITE_CODE ON unite (code)');

        $this->addSql(<<<'SQL'
            INSERT INTO unite (code, libelle, actif, position) VALUES
                ('u', 'Unite', true, 0),
                ('forfait', 'Forfait', true, 1),
                ('ens', 'Ensemble', true, 2),
                ('m2', 'Metre carre', true, 3),
                ('ml', 'Metre lineaire', true, 4),
                ('m3', 'Metre cube', true, 5),
                ('kg', 'Kilogramme', true, 6),
                ('t', 'Tonne', true, 7),
                ('h', 'Heure', true, 8),
                ('j', 'Jour', true, 9),
                ('L', 'Litre', true, 10)
            SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE unite');
    }
}
